In [55]:
import pandas as pd

In [88]:
df= pd.read_excel('C:\\Users\\sidlu\\Mauritius_Tourism_Analytics\\data\\raw\\HS_Tourism_Yr25_220526.xls', sheet_name="Table 2 ", header=None)

In [69]:
df

,0,1,2,3,4,5,6,7,8,9,...,34,35,36,37,38,39,40,41,42,43
0,Back to Table of Contents,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Table 2 - Departure 1 of Mauritian residents b...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Country of disembarkation,1983,1984,1985,1986,1987,1988,1989,1990,1991,...,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025
4,Australia,1120,1110,1090,1470,2000,1530,100,1260,1360,...,8019,8411,8848,8362,2042,n.ap,2412,9262,9214,9606
5,Belgium,150,130,160,350,270,220,20,360,370,...,n.ap,n.ap,n.ap,n.ap,n.ap,184,2369,1559,n.ap,n.ap
6,Canada,280,170,170,130,320,190,0,460,430,...,n.ap,n.ap,n.ap,n.ap,n.ap,n.ap,n.ap,n.ap,n.ap,n.ap
7,France,3620,4270,4130,4110,4040,5390,8320,7820,6570,...,31546,29268,28925,29683,8814,13540,36667,41187,35884,36546
8,Germany,900,1000,1320,1000,1560,1220,2280,1140,870,...,2440,3334,3904,3265,647,369,2660,3838,6276,5738
9,Hong Kong SAR 3,550,720,740,630,800,520,400,1460,1540,...,4596,4807,5090,5874,307,n.ap,n.ap,n.ap,n.ap,n.ap
10,India,2520,2400,2460,2270,2300,2670,3660,4740,4910,...,20848,22493,26607,31232,7320,2087,18187,31260,39354,53860
11,Italy,640,600,400,540,950,1460,650,1650,1740,...,1365,1873,856,890,576,n.ap,14,301,172,462
12,Kenya,n.ap,n.ap,n.ap,n.ap,n.ap,n.ap,n.ap,n.ap,n.ap,...,2776,2514,4205,8807,1491,741,7071,8444,7157,7999
13,Malagasy Republic,n.ap,n.ap,n.ap,n.ap,n.ap,n.ap,n.ap,n.ap,n.ap,...,9378,8418,8833,10701,2441,479,6824,10072,10945,11822
14,Malaysia,n.ap,n.ap,n.ap,n.ap,n.ap,n.ap,n.ap,n.ap,n.ap,...,12912,5281,1670,2323,354,n.ap,3428,14420,17507,20062
15,Netherlands,n.ap,n.ap,n.ap,n.ap,n.ap,n.ap,n.ap,n.ap,n.ap,...,n.ap,158,1812,1603,n.ap,n.ap,1,n.ap,n.ap,n.ap
16,People's Rep. of China,n.ap,n.ap,n.ap,n.ap,n.ap,n.ap,n.ap,n.ap,n.ap,...,3708,5731,2503,2155,144,43,1,n.ap,n.ap,n.ap
17,Reunion Island,13450,14240,15230,15040,13580,17120,22570,25950,23680,...,34228,43561,40081,42719,7842,2991,31464,42127,43625,45684
18,Saudi Arabia,n.ap,n.ap,n.ap,n.ap,n.ap,n.ap,n.ap,n.ap,n.ap,...,n.ap,1468,5472,5362,548,159,6832,13450,17617,16647
19,Seychelles,n.ap,n.ap,n.ap,n.ap,n.ap,n.ap,n.ap,n.ap,n.ap,...,10383,10703,9509,8770,1941,639,3075,4314,4825,6011
20,Singapore,n.ap,n.ap,760,1510,6580,9640,13020,8870,9470,...,9537,14974,15714,15973,1430,n.ap,17,1,n.ap,n.ap
21,"South Africa, Rep. of",2100,2370,2410,2910,3100,3330,4040,4440,4480,...,26411,27751,29002,32155,6971,1724,16539,26918,28854,32270
22,Switzerland,220,520,700,860,740,580,690,1190,760,...,118,675,1166,1912,744,201,1715,2080,2945,2513
23,Turkey,n.ap,n.ap,n.ap,n.ap,n.ap,n.ap,n.ap,n.ap,n.ap,...,2675,6390,10813,13639,1624,1756,10737,10091,14119,14766
24,United Arab Emirates,n.ap,n.ap,n.ap,n.ap,n.ap,n.ap,n.ap,n.ap,n.ap,...,61765,64558,70193,72857,14973,14126,58948,73888,85131,92882
25,United Kingdom,4750,4740,4420,5070,5080,6120,6990,8080,7410,...,17414,19423,19698,20704,4997,3171,19471,25488,25294,22617
26,Zimbabwe,n.ap,n.ap,n.ap,n.ap,n.ap,n.ap,n.ap,n.ap,n.ap,...,n.ap,n.ap,1,n.ap,n.ap,n.ap,n.ap,n.ap,n.ap,n.ap
27,Others & not stated,4470,4728,5193,4640,5815,6740,5540,8880,7880,...,348,973,1181,1192,263,236,836,1025,1241,1030
28,All countries,34770,36998,39183,40530,47135,56730,68280,76300,71470,...,260467,282764,296083,320178,65469,42446,229268,319725,350160,380515
29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,"Source: Administrative data, Passport and Immi...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,1 Excludes inter-island traffic between the is...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,2 Disembarkation may either be the country of ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,3 Special Administrative Region of China,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,n.ap: not applicable,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
42,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
43,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
45,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
46,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
48,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9,NaN

In [95]:
df.drop(range(0,3))

,0,1,2,3,4,5,6,7,8,9,...,34,35,36,37,38,39,40,41,42,43
3,Country of disembarkation,1983,1984,1985,1986,1987,1988,1989,1990,1991,...,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025
4,Australia,1120,1110,1090,1470,2000,1530,100,1260,1360,...,8019,8411,8848,8362,2042,n.ap,2412,9262,9214,9606
5,Belgium,150,130,160,350,270,220,20,360,370,...,n.ap,n.ap,n.ap,n.ap,n.ap,184,2369,1559,n.ap,n.ap
6,Canada,280,170,170,130,320,190,0,460,430,...,n.ap,n.ap,n.ap,n.ap,n.ap,n.ap,n.ap,n.ap,n.ap,n.ap
7,France,3620,4270,4130,4110,4040,5390,8320,7820,6570,...,31546,29268,28925,29683,8814,13540,36667,41187,35884,36546
8,Germany,900,1000,1320,1000,1560,1220,2280,1140,870,...,2440,3334,3904,3265,647,369,2660,3838,6276,5738
9,Hong Kong SAR 3,550,720,740,630,800,520,400,1460,1540,...,4596,4807,5090,5874,307,n.ap,n.ap,n.ap,n.ap,n.ap
10,India,2520,2400,2460,2270,2300,2670,3660,4740,4910,...,20848,22493,26607,31232,7320,2087,18187,31260,39354,53860
11,Italy,640,600,400,540,950,1460,650,1650,1740,...,1365,1873,856,890,576,n.ap,14,301,172,462
12,Kenya,n.ap,n.ap,n.ap,n.ap,n.ap,n.ap,n.ap,n.ap,n.ap,...,2776,2514,4205,8807,1491,741,7071,8444,7157,7999
13,Malagasy Republic,n.ap,n.ap,n.ap,n.ap,n.ap,n.ap,n.ap,n.ap,n.ap,...,9378,8418,8833,10701,2441,479,6824,10072,10945,11822
14,Malaysia,n.ap,n.ap,n.ap,n.ap,n.ap,n.ap,n.ap,n.ap,n.ap,...,12912,5281,1670,2323,354,n.ap,3428,14420,17507,20062
15,Netherlands,n.ap,n.ap,n.ap,n.ap,n.ap,n.ap,n.ap,n.ap,n.ap,...,n.ap,158,1812,1603,n.ap,n.ap,1,n.ap,n.ap,n.ap
16,People's Rep. of China,n.ap,n.ap,n.ap,n.ap,n.ap,n.ap,n.ap,n.ap,n.ap,...,3708,5731,2503,2155,144,43,1,n.ap,n.ap,n.ap
17,Reunion Island,13450,14240,15230,15040,13580,17120,22570,25950,23680,...,34228,43561,40081,42719,7842,2991,31464,42127,43625,45684
18,Saudi Arabia,n.ap,n.ap,n.ap,n.ap,n.ap,n.ap,n.ap,n.ap,n.ap,...,n.ap,1468,5472,5362,548,159,6832,13450,17617,16647
19,Seychelles,n.ap,n.ap,n.ap,n.ap,n.ap,n.ap,n.ap,n.ap,n.ap,...,10383,10703,9509,8770,1941,639,3075,4314,4825,6011
20,Singapore,n.ap,n.ap,760,1510,6580,9640,13020,8870,9470,...,9537,14974,15714,15973,1430,n.ap,17,1,n.ap,n.ap
21,"South Africa, Rep. of",2100,2370,2410,2910,3100,3330,4040,4440,4480,...,26411,27751,29002,32155,6971,1724,16539,26918,28854,32270
22,Switzerland,220,520,700,860,740,580,690,1190,760,...,118,675,1166,1912,744,201,1715,2080,2945,2513
23,Turkey,n.ap,n.ap,n.ap,n.ap,n.ap,n.ap,n.ap,n.ap,n.ap,...,2675,6390,10813,13639,1624,1756,10737,10091,14119,14766
24,United Arab Emirates,n.ap,n.ap,n.ap,n.ap,n.ap,n.ap,n.ap,n.ap,n.ap,...,61765,64558,70193,72857,14973,14126,58948,73888,85131,92882
25,United Kingdom,4750,4740,4420,5070,5080,6120,6990,8080,7410,...,17414,19423,19698,20704,4997,3171,19471,25488,25294,22617
26,Zimbabwe,n.ap,n.ap,n.ap,n.ap,n.ap,n.ap,n.ap,n.ap,n.ap,...,n.ap,n.ap,1,n.ap,n.ap,n.ap,n.ap,n.ap,n.ap,n.ap
27,Others & not stated,4470,4728,5193,4640,5815,6740,5540,8880,7880,...,348,973,1181,1192,263,236,836,1025,1241,1030
28,All countries,34770,36998,39183,40530,47135,56730,68280,76300,71470,...,260467,282764,296083,320178,65469,42446,229268,319725,350160,380515
29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,"Source: Administrative data, Passport and Immi...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,1 Excludes inter-island traffic between the is...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,2 Disembarkation may either be the country of ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,3 Special Administrative Region of China,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,n.ap: not applicable,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
42,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
43,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
45,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
46,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
48,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9,NaN

In [138]:

df= pd.read_excel('C:\\Users\\sidlu\\Mauritius_Tourism_Analytics\\data\\raw\\HS_Tourism_Yr25_220526.xls', sheet_name="Table 2 ", header=None)

df.columns=df.iloc[3]

df.columns.name=None

df=df.drop(range(0,4)).reset_index(drop=True)

df = df.melt(
    id_vars='Country of disembarkation',   # column(s) to keep as-is
    var_name='Year',                        # name for the new "year" column
    value_name='Arrivals'                   # name for the new "value" column
)
df=df.sort_values(["Country of disembarkation","Year"]).reset_index(drop=True)

df.head(50)

   Country of disembarkation  Year Arrivals
0                  Australia  1983     1120
1                  Australia  1984     1110
2                  Australia  1985     1090
3                  Australia  1986     1470
4                  Australia  1987     2000
5                  Australia  1988     1530
6                  Australia  1989      100
7                  Australia  1990     1260
8                  Australia  1991     1360
9                  Australia  1992     1800
10                 Australia  1993     1770
11                 Australia  1994     3012
12                 Australia  1995     2817
13                 Australia  1996     3799
14                 Australia  1997     3610
15                 Australia  1998     3326
16                 Australia  1999     3813
17                 Australia  2000     4696
18                 Australia  2001     4525
19                 Australia  2002     4705
20                 Australia  2003     5250
21                 Australia  2004     6760
22                 Australia  2005     7000
23                 Australia  2006     7904
24                 Australia  2007     9980
25                 Australia  2008    13310
26                 Australia  2009     8514
27                 Australia  2010     8690
28                 Australia  2011     9534
29                 Australia  2012     9251
30                 Australia  2013     7982
31                 Australia  2014     7281
32                 Australia  2015     8040
33                 Australia  2016     8019
34                 Australia  2017     8411
35                 Australia  2018     8848
36                 Australia  2019     8362
37                 Australia  2020     2042
38                 Australia  2021     n.ap
39                 Australia  2022     2412
40                 Australia  2023     9262
41                 Australia  2024     9214
42                 Australia  2025     9606
43                   Belgium  1983      150
44                   Belgium  1984      130
45                   Belgium  1985      160
46                   Belgium  1986      350
47                   Belgium  1987      270
48                   Belgium  1988      220
49                   Belgium  1989       20

In [153]:
rows_to_remove = ['All countries', 'Others & not stated', '\"Source: Administrative data, Passport and Immigration Office\"', '2 Disembarkation may either be the country of final destination or the transit country', '1 Excludes inter-island traffic between the islands of Mauritius and Rodrigues', '3 Special Administrative Region of China', 'n.ap: not applicable']

df=df[~df['Country of disembarkation'].isin(rows_to_remove)]

df = df[df['Country of disembarkation'].notna()]

df = df[~df['Country of disembarkation'].str.startswith('Source:', na=False)]

In [154]:
df.to_csv("C:\\Users\\sidlu\\Mauritius_Tourism_Analytics\\data\\processed\\HS_Tourism_Clean.CSV", index=False)